name: Level 1 - Yoshi's Island

on:
  workflow_dispatch: {} # TODO: Bonus opdracht, vervang door een echte trigger.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

        # TODO - Configureer JDK 21 - hint: wellicht ook iets met actions?
      - name: Configure JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin

        # TODO - Setup Gradle
      - name: Setup Grade
        uses: gradle/actions/setup-gradle@latest

        # TODO - Run een gradle build command
      - name: Build using configured Java and Gradle dist
        run: ./gradlew build
